# test of travis ci for comblayer
language: cpp
os:
  - linux
compiler:
  - gcc
  - clang 
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      - gcc
      - build-essential
      - libboost-regex-dev
      - libgsl0-dev
      - libboost-dev
      - libboost-filesystem-dev
before_install:
  - cmake -version
  - gcc --version
  - sudo apt-get update
script:
  - ./CMake.pl -O -g++=$CXX
  - cmake ./
  - make -j6
  - ./testMain -1 -1 -1
  - ./fullBuild -r fbtest 


  
